server:
  port: 5000

info:
  artifactId: "${project.name}"
  version: "${project.version}"

spring:
  application:
    name: Bet-Service
  datasource:
    url: jdbc:mysql://bet-service-database.cksw6zblgipq.us-east-1.rds.amazonaws.com/betdb
    username: root
    password: 'BrenoLopesERodinei'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Hawtio
hawtio:
  authenticationEnabled: false