INSERT INTO rule(type, name)
VALUES ('ANALYSIS', 'CHECK_RESULT');

INSERT INTO rule(type, name)
VALUES ('ANALYSIS', 'CHECK_CORNER_FREQUENCY');

INSERT INTO rule(type, name)
VALUES ('ANALYSIS', 'CHECK_FREQUENCY_ENTRIES');

INSERT INTO rule(type, name)
VALUES ('ANALYSIS', 'CHECK_INJURY_TIME');

INSERT INTO rule(type, name)
VALUES ('ANALYSIS', 'CHECK_LEAGUE_TYPE');